server:
  address: 0.0.0.0

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: http://localhost:8081
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1

            - id: evaluation-service
              uri: http://localhost:8083
              predicates:
                - Path=/evaluation/**
              filters:
                - StripPrefix=1

            - id: user-service
              uri: http://localhost:8082
              predicates:
                - Path=/user/**
              filters:
                - StripPrefix=1

            - id: emotion-service
              uri: http://localhost:8086
              predicates:
                - Path=/emotion/**
              filters:
                - StripPrefix=1

            - id: admin-service
              uri: http://localhost:8084
              predicates:
                - Path=/admin/**
              filters:
                - StripPrefix=1

            - id: goals-service
              uri: http://localhost:8085
              predicates:
                - Path=/goals/**
              filters:
                - StripPrefix=1

            - id: notification-service
              uri: http://localhost:8087
              predicates:
                - Path=/notification/**
              filters:
                - StripPrefix=1

            - id: storage-service
              uri: http://localhost:8088
              predicates:
                - Path=/storage/**
              filters:
                - StripPrefix=1

---
spring:
  config:
    activate:
      on-profile: mobile

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: http://192.168.1.105:8081
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1

            - id: evaluation-service
              uri: http://192.168.1.105:8083
              predicates:
                - Path=/evaluation/**
              filters:
                - StripPrefix=1

            - id: user-service
              uri: http://192.168.1.105:8082
              predicates:
                - Path=/user/**
              filters:
                - StripPrefix=1

            - id: emotion-service
              uri: http://192.168.1.105:8086
              predicates:
                - Path=/emotion/**
              filters:
                - StripPrefix=1

            - id: admin-service
              uri: http://192.168.1.105:8084
              predicates:
                - Path=/admin/**
              filters:
                - StripPrefix=1

            - id: goals-service
              uri: http://192.168.1.105:8085
              predicates:
                - Path=/goals/**
              filters:
                - StripPrefix=1

            - id: notification-service
              uri: http://192.168.1.105:8087
              predicates:
                - Path=/notification/**
              filters:
                - StripPrefix=1

            - id: storage-service
              uri: http://192.168.1.105:8088
              predicates:
                - Path=/storage/**
              filters:
                - StripPrefix=1

test:
  message: "Hola YML cargado!"
